'use client';
import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Brain,ChartNoAxesCombined,Clock3,Flame,Home,Layers,LogOut,Play,Target,Trophy,User,Users} from 'lucide-react';
import {Mascot} from '../pet';
import styles from './demo.module.css';

const nav=[{label:'Hoje',icon:Home},{label:'Estudar',icon:BookOpen},{label:'Comunidade',icon:Users},{label:'Progresso',icon:ChartNoAxesCombined},{label:'Perfil',icon:User}];

export default function DemoNivoStudy(){
 const [page,setPage]=useState('Hoje');
 const [seconds,setSeconds]=useState(0);
 const [running,setRunning]=useState(false);
 useEffect(()=>{if(localStorage.getItem('nivostudy-demo')!=='1'){window.location.replace('/login');return}const t=running?setInterval(()=>setSeconds(v=>v+1),1000):undefined;return()=>{if(t)clearInterval(t)}},[running]);
 const time=useMemo(()=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`,[seconds]);
 const logout=()=>{localStorage.removeItem('nivostudy-demo');localStorage.removeItem('nivostudy-demo-email');window.location.assign('/login')};
 const email=typeof window!=='undefined'?localStorage.getItem('nivostudy-demo-email')||'demo@nivostudy.app':'demo@nivostudy.app';
 return <div className={styles.shell}>
  <aside className={styles.side}><div className={styles.brand}><span className={styles.mark}>N</span>NivoStudy<span className={styles.demo}>DEMO</span></div><nav className={styles.nav}>{nav.map(({label,icon:Icon})=><button key={label} className={page===label?styles.active:''} onClick={()=>setPage(label)}><Icon size={18}/>{label}</button>)}</nav><button className={styles.logout} onClick={logout}><LogOut size={17}/>Sair do modo demo</button></aside>
  <main className={styles.main}>
   <header className={styles.top}><div><p className={styles.eyebrow}>NivoStudy · acesso temporário</p><h1>{page}</h1></div><span className={styles.mode}>Código 000000 · modo demo</span></header>
   <div className={styles.content}>
    {page==='Hoje'&&<><section className={styles.hero}><div><p className={styles.eyebrow}>Seu ritmo de hoje</p><h2>Estude sem transformar progresso em pressão.</h2><p>O NivoStudy organiza foco, revisão e evolução em um espaço simples. Este acesso é uma demonstração isolada.</p></div><div className={styles.pet}><Mascot mood="happy"/></div></section><div className={styles.stats}><div className={styles.stat}><strong>42 min</strong><span>foco hoje</span></div><div className={styles.stat}><strong>3/5</strong><span>meta semanal</span></div><div className={styles.stat}><strong>7</strong><span>dias de ritmo</span></div></div><div className={styles.sectionHead}><h2>Escolha o próximo passo</h2><span>sem feed obrigatório</span></div><div className={styles.tools}>{[{t:'Foco',d:'Cronômetro para uma matéria.',i:Clock3},{t:'Quiz',d:'Teste rápido do que você estudou.',i:Brain},{t:'Revisão',d:'Volte no conteúdo certo.',i:Layers}].map(({t,d,i:Icon})=><button className={styles.tool} key={t} onClick={()=>setPage('Estudar')}><Icon size={21}/><strong>{t}</strong><span>{d}</span></button>)}</div><div className={styles.sectionHead}><h2>Atividade recente</h2><span>somente exemplo</span></div><div className={styles.feed}><div className={styles.activity}><span className={styles.activityIcon}><BookOpen size={18}/></span><div><strong>Ciências · Reações químicas</strong><span>25 min de foco</span></div><span className={styles.xp}>+10 XP</span></div><div className={styles.activity}><span className={styles.activityIcon}><Target size={18}/></span><div><strong>Matemática · Equações</strong><span>8 questões · 75% de acertos</span></div><span className={styles.xp}>+34 XP</span></div></div></>}
    {page==='Estudar'&&<div className={styles.studyPanel}><section className={styles.timer}><div><p className={styles.eyebrow}>Sessão rápida</p><strong>{time}</strong><p>Ciências · Reações químicas</p></div><div className={styles.timerActions}><button className={styles.primary} onClick={()=>setRunning(v=>!v)}>{running?'Pausar':'Começar'}</button><button className={styles.secondary} onClick={()=>{setRunning(false);setSeconds(0)}}>Zerar</button></div></section><div className={styles.stack}><div className={styles.mini}><Brain size={20}/><h3>Quiz rápido</h3><p>Na versão conectada, questões e resultados ficam salvos no seu histórico.</p></div><div className={styles.mini}><Layers size={20}/><h3>Flashcards</h3><p>Revisões aparecem quando fizer sentido voltar ao conteúdo.</p></div><div className={styles.mini}><Target size={20}/><h3>Objetivo simples</h3><p>Uma meta curta por sessão, sem sobrecarregar a tela.</p></div></div></div>}
    {page==='Comunidade'&&<><section className={styles.hero}><div><p className={styles.eyebrow}>Comunidade com controle</p><h2>Compartilhe evolução só quando quiser.</h2><p>O NivoStudy parte do privado. Atividades só entram na comunidade quando o usuário escolher publicar.</p></div><Users className={styles.pet} size={72}/></section><div className={styles.notice}>No modo demo, nenhuma atividade é publicada e nenhum usuário real é exibido.</div></>}
    {page==='Progresso'&&<><div className={styles.stats}><div className={styles.stat}><strong>4h 18</strong><span>esta semana</span></div><div className={styles.stat}><strong>76%</strong><span>acertos</span></div><div className={styles.stat}><strong>214</strong><span>XP</span></div></div><div className={styles.sectionHead}><h2>Matérias</h2><span>exemplo de leitura rápida</span></div><div className={styles.progressList}>{[['Ciências',82],['Matemática',64],['Português',71],['História',56]].map(([name,value])=><div className={styles.progressRow} key={String(name)}><div className={styles.progressTop}><span>{name}</span><strong>{value}%</strong></div><div className={styles.bar}><i style={{width:`${value}%`}}/></div></div>)}</div></>}
    {page==='Perfil'&&<><section className={styles.profile}><div className={styles.avatar}>N</div><div><h2>Perfil de demonstração</h2><p>@nivostudy_demo · {email}</p></div></section><div className={styles.notice}>O código <strong>000000</strong> não autentica uma conta real. Ele abre somente este ambiente isolado, sem acesso ao Supabase, dados pessoais ou perfis de outras pessoas.</div><div className={styles.sectionHead}><h2>Identidade NivoStudy</h2><span>ritmo, foco e progresso</span></div><div className={styles.tools}><div className={styles.card}><Flame size={20}/><strong>Ritmo</strong></div><div className={styles.card}><Trophy size={20}/><strong>Conquistas</strong></div><div className={styles.card}><Play size={20}/><strong>Começar simples</strong></div></div></>}
   </div>
  </main>
  <nav className={styles.mobileNav}>{nav.map(({label,icon:Icon})=><button key={label} className={page===label?styles.active:''} onClick={()=>setPage(label)}><Icon size={18}/><span>{label}</span></button>)}</nav>
 </div>
}
