'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Eye,EyeOff,Mail,LockKeyhole} from 'lucide-react';
import {Mascot} from './pet';
export default function AuthForm({mode,onBack,onSignedIn}:{mode:'login'|'signup';onBack:()=>void;onSignedIn:()=>void}){
 const [view,setView]=useState<'login'|'signup'|'recover'|'confirm'>(mode),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[cooldown,setCooldown]=useState(0);
 const request=async(action:string)=>{if(busy)return;setError('');setNotice('');if(action==='signup'&&password!==repeat){setError('As senhas precisam ser iguais.');return}setBusy(true);try{const res=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email,password})}),data:any=await res.json();if(!res.ok)throw Error(data.error);setPassword('');setRepeat('');if(data.confirmation){setView('confirm');setCooldown(Date.now()+60000)}else if(data.sent){setNotice('Se o e-mail estiver cadastrado, você receberá um link. Confira também o spam.');setCooldown(Date.now()+60000)}else onSignedIn()}catch(e){setError(e instanceof Error?e.message:'Não foi possível continuar.')}finally{setBusy(false)}};
 return <main className="entry-screen auth-screen"><header className="entry-header"><button aria-label="Voltar" onClick={onBack} disabled={busy}><ArrowLeft size={20}/></button><span>NIVOSTUDY</span><span/></header><section className="auth-card"><div className="auth-pet"><Mascot mood={busy?'thinking':view==='confirm'?'happy':'idle'}/></div><p className="eyebrow">UM PASSO DE CADA VEZ</p><h1>{view==='signup'?'Seu começo é aqui.':view==='recover'?'Vamos recuperar seu acesso.':view==='confirm'?'Confira seu e-mail.':'Bom ter você de volta.'}</h1><p className="auth-description">{view==='signup'?'Crie sua conta. Depois, o pet ajuda a montar seu espaço.':view==='recover'?'Enviaremos um link para você escolher uma nova senha.':view==='confirm'?`Abra o link enviado para ${email} e volte para entrar.`:'Entre para continuar seus estudos e suas conquistas.'}</p>
 {view==='confirm'?<div className="auth-confirm"><div className="auth-mail"><Mail size={24}/></div><button className="primary" disabled={busy} onClick={()=>{setView('login');setError('');setNotice('')}}>Já confirmei, entrar <ArrowRight size={17}/></button><button className="ghost" disabled={busy} onClick={()=>Date.now()<cooldown?setNotice('Aguarde um minuto antes de reenviar.'):request('resend')}>Reenviar e-mail</button></div>:<form onSubmit={e=>{e.preventDefault();void request(view)}}><label htmlFor="auth-email">E-mail</label><div className="auth-input"><Mail size={17}/><input id="auth-email" type="email" autoComplete="email" autoCapitalize="none" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@exemplo.com" disabled={busy}/></div>{view!=='recover'&&<><label htmlFor="auth-password">Senha</label><div className="auth-input"><LockKeyhole size={17}/><input id="auth-password" type={show?'text':'password'} autoComplete={view==='signup'?'new-password':'current-password'} required minLength={view==='signup'?8:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} placeholder={view==='signup'?'Pelo menos 8 caracteres':'Sua senha'} disabled={busy}/><button type="button" className="password-toggle" aria-label={show?'Ocultar senha':'Mostrar senha'} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{view==='signup'&&<><label htmlFor="auth-repeat">Confirmar senha</label><div className="auth-input"><LockKeyhole size={17}/><input id="auth-repeat" type={show?'text':'password'} autoComplete="new-password" required minLength={8} maxLength={128} value={repeat} onChange={e=>setRepeat(e.target.value)} placeholder="Digite a senha novamente" disabled={busy}/></div><p className="auth-hint">Use uma senha exclusiva para sua conta.</p></>}{view==='login'&&<button type="button" className="auth-forgot" disabled={busy} onClick={()=>{setView('recover');setError('');setNotice('');setPassword('')}}>Esqueci minha senha</button>}</>}
 <button className="primary" type="submit" disabled={busy}>{busy?<><span className="thinking-dots" aria-hidden="true"><i/><i/><i/></span><span role="status">{view==='recover'?'Enviando…':'Só um instante…'}</span></>:<>{view==='signup'?'Criar minha conta':view==='recover'?'Enviar link':'Entrar'}<ArrowRight size={17}/></>}</button></form>}
 {error&&<p className="entry-error" role="alert">{error}</p>}{notice&&<p className="auth-notice" role="status">{notice}</p>}<div className="auth-switch">{view==='recover'?<button disabled={busy} onClick={()=>{setView('login');setNotice('');setError('')}}>Voltar ao login</button>:<a href={view==='login'?'/criar-conta':'/login'}>{view==='login'?'Ainda não tem conta? Criar conta':'Já tem uma conta? Entrar'}</a>}</div><p className="auth-footnote">Seu progresso fica salvo na sua conta.</p></section></main>
}
