'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,Layers,Mic,Timer} from 'lucide-react';
import AuthForm from './auth-form';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
export {Mascot,LoadingPet} from './pet';
import {Mascot,LoadingPet} from './pet';
const questions=['Qual seu nome?','Quer escolher suas matérias agora?','O que você quer estudar?','Quantos dias por semana combinam com você?','Qual vai ser seu nome de usuário?'];
const options=['Ciências','Matemática','Português','História'];
const collage=['Reações químicas','Um assunto por vez','Seu ritmo','Guerra Fria','Mais uma revisão','Matemática','Uma ideia nova','Conquista de hoje','Perguntar. Aprender.'];
function QuestionText({text,animate}:{text:string;animate:boolean}){
 const [count,setCount]=useState(animate?0:text.length);
 useEffect(()=>{if(!animate)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setCount(text.length);return}setCount(0);let start=performance.now();let frame:number;const tick=(now:number)=>{setCount(Math.min(text.length,Math.floor((now-start)/18)));if((now-start)/18<text.length)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[text,animate]);
 return <p>{animate?text.slice(0,count):text}</p>;
}
function GoogleMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M21.6 12.2c0-.7-.1-1.4-.2-2.1H12v4h5.4a4.5 4.5 0 0 1-2 3v2.6h3.3c1.9-1.7 2.9-4.3 2.9-7.5Z"/><path fill="currentColor" d="M12 22c2.7 0 5-1 6.7-2.4l-3.3-2.6c-.9.6-2 1-3.4 1-2.6 0-4.8-1.8-5.6-4.1H3v2.7A10 10 0 0 0 12 22ZM6.4 13.9A6 6 0 0 1 6 12c0-.7.1-1.3.4-1.9V7.4H3A10 10 0 0 0 2 12c0 1.6.4 3.2 1 4.6l3.4-2.7ZM12 6c1.5 0 2.8.5 3.8 1.5l2.9-2.9A9.8 9.8 0 0 0 12 2a10 10 0 0 0-9 5.4l3.4 2.7C7.2 7.8 9.4 6 12 6Z"/></svg>}
function AppleMark(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M16.9 12.9c0-2 1.6-3 1.7-3.1a3.8 3.8 0 0 0-3-1.6c-1.3-.1-2.5.8-3.1.8-.7 0-1.7-.8-2.8-.7-1.5 0-2.9.8-3.6 2.1-1.5 2.6-.4 6.4 1.1 8.5.7 1 1.5 2.1 2.6 2.1 1.1-.1 1.5-.7 2.9-.7 1.3 0 1.7.7 2.9.7 1.2 0 1.9-1 2.6-2.1.8-1.2 1.1-2.3 1.2-2.4-.1 0-2.5-1-2.5-3.6ZM15 6.8c.6-.8 1.1-1.9 1-3-.9 0-2 .6-2.7 1.4-.6.7-1.2 1.8-1.1 2.9 1 .1 2.1-.5 2.8-1.3Z"/></svg>}
export default function Entry({mode='welcome',authenticated=true,initialName='',onComplete}:{mode?:'welcome'|'login'|'create';authenticated?:boolean;initialName?:string;onComplete?:()=>void}){
 const [stage,setStage]=useState(mode==='create'&&authenticated?'questions':'welcome'),[step,setStep]=useState(0),[name,setName]=useState(initialName),[personalize,setPersonalize]=useState<boolean|null>(null),[handle,setHandle]=useState(''),[subjects,setSubjects]=useState<string[]>([]),[days,setDays]=useState(5),[busy,setBusy]=useState(false),[error,setError]=useState(''),[thinking,setThinking]=useState(false),[height,setHeight]=useState<number|null>(null),[voiceSupported,setVoiceSupported]=useState(false),[listening,setListening]=useState(false);
 const end=useRef<HTMLDivElement>(null),speech=useRef<any>(null);
 const flow=personalize===false?[0,1,3,4]:[0,1,2,3,4];
 useEffect(()=>{const viewport=window.visualViewport;const resize=()=>setHeight(viewport?.height??window.innerHeight);resize();viewport?.addEventListener('resize',resize);setVoiceSupported(!!((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition));return()=>{viewport?.removeEventListener('resize',resize);speech.current?.abort()}},[]);
 useEffect(()=>{if(stage==='questions'){setThinking(true);const timer=setTimeout(()=>setThinking(false),380);return()=>clearTimeout(timer)}},[step,stage]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'end'})},[step,thinking,error]);
 const begin=()=>{if(mode==='login'&&authenticated)window.location.assign('/');else if(!authenticated)setStage('auth');else setStage('questions')};
 const responses=[name,personalize?'Sim':'Agora não',subjects.join(' · '),`${days} dias por semana`,'@'+handle];
 const valid=step===0?name.trim().length>=2:step===1?personalize!==null:step===2?subjects.length>0:step===4?/^[a-z0-9_]{3,24}$/.test(handle):true;
 const next=()=>{if(!valid||thinking)return;setError('');setStep(flow[flow.indexOf(step)+1]??5)};
 const chooseRoutine=(value:boolean)=>{setPersonalize(value);if(!value)setSubjects(options);setStep(value?2:3);setError('')};
 const back=()=>{setError('');if(step===5)setStep(4);else if(step===0)setStage('welcome');else setStep(flow[Math.max(0,flow.indexOf(step)-1)])};
 const voice=()=>{if(listening){speech.current?.stop();return}const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech)return;const recognition=new Speech();speech.current=recognition;recognition.lang='pt-BR';recognition.interimResults=false;recognition.onresult=(event:any)=>{const text=event.results[0][0].transcript;if(step===0)setName(text.slice(0,40));else setHandle(text.toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,24))};recognition.onend=()=>setListening(false);recognition.onerror=()=>{setListening(false);setError('Não foi possível ouvir. Você pode digitar sua resposta.')};setListening(true);recognition.start()};
 const save=async()=>{if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/nivora',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'profile',nickname:name.trim(),handle,subjects,goal:days})});const body=await response.json() as {signIn?:boolean;error?:string};if(!response.ok){if(body.signIn){window.location.assign('/criar-conta');return}throw Error(body.error??'Não foi possível salvar.')}setStage('done');if(onComplete)onComplete();else window.location.assign('/')}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');setBusy(false)}};
 if(stage==='auth')return <AuthForm mode={mode==='login'?'login':'signup'} onBack={()=>setStage('welcome')} onSignedIn={()=>{mode==='login'?window.location.assign('/'):setStage('questions')}}/>;
 if(stage==='welcome')return <main className="entry-screen entry-welcome reference-welcome"><div className="study-collage" aria-hidden="true">{collage.map((title,i)=>{const Icon=i%3===0?BookOpen:i%3===1?Layers:Timer;return <div className={`collage-card collage-${i%3}`} key={title}><Icon/><small>NIVOSTUDY</small><strong>{title}</strong><div className="collage-lines"><span/><span/></div></div>})}</div><div className="reference-welcome-content"><div className="welcome-pet"><Mascot/></div><h1>Cada estudo.<br/>Cada conquista.<br/>No seu ritmo.</h1><div className="reference-providers"><button disabled title="Disponível em breve" aria-label="Entrar com Apple, disponível em breve"><AppleMark/></button><button disabled title="Disponível em breve" aria-label="Entrar com Google, disponível em breve"><GoogleMark/></button></div><button className="use-email" onClick={begin}>Usar email</button><a className="welcome-account" href={mode==='login'?'/criar-conta':'/login'}>{mode==='login'?'Criar conta':'Já tem conta? Entrar'}</a></div><span className="welcome-wordmark">nivo<span>study</span><i>.</i></span></main>;
 if(stage==='done')return <main className="entry-screen completion-screen"><Mascot mood="happy"/><h1>Seu espaço está pronto.</h1><p>Um assunto por vez. Uma conquista de cada vez.</p><a href="/" className="email-continue">Começar</a></main>;
 return <main className="entry-screen entry-conversation reference-conversation" style={height?{height,minHeight:0}:undefined}>
  <Progress className="entry-progress" value={(step===5?flow.length+1:flow.indexOf(step)+1)/(flow.length+1)*100} aria-label="Progresso de criação do perfil"/>
  <div className={`conversation-pet ${thinking?'pet-turning':''}`}><Mascot mood={busy||thinking?'thinking':step===5?'happy':'idle'}/></div>
  <div className="entry-messages" aria-live="polite">{flow.filter(i=>i<=step).map(i=><div className="conversation-turn" key={i}>
   <QuestionText text={questions[i]} animate={i===step}/>
   {i===step&&<p className="question-hint">{i===0?'Pode ser seu primeiro nome ou um apelido.':i===1?'Responda “sim” ou “agora não”.':i===2?'Escolha as matérias que quer ter por perto.':i===3?'Uma meta flexível, com tempo para descansar.':'Use de 3 a 24 letras, números ou _.'}</p>}
   {i<step&&<div className="answer-bubble">{responses[i]}</div>}
  </div>)}
  {thinking?<div className="thinking-dots" aria-label="Preparando a próxima pergunta"><i/><i/><i/></div>:step===1?<RadioGroup className="conversation-choices" value="" onValueChange={value=>chooseRoutine(value==='yes')} aria-label={questions[1]}><label><RadioGroupItem value="yes" className="conversation-choice-radio"/>Sim, quero escolher</label><label><RadioGroupItem value="no" className="conversation-choice-radio"/>Agora não</label></RadioGroup>:step===2?<div className="conversation-choices" role="group" aria-label="Matérias">{options.map(s=><label key={s} className={subjects.includes(s)?'choice-selected':''}><span>{s}</span><Checkbox checked={subjects.includes(s)} onCheckedChange={checked=>setSubjects(current=>checked?[...current,s]:current.filter(x=>x!==s))} aria-label={s}/></label>)}</div>:step===3?<RadioGroup className="conversation-choices" value="" onValueChange={value=>{setDays(Number(value));setStep(4)}} aria-label="Dias de estudo">{[3,4,5,6,7].map(d=><label key={d}><RadioGroupItem value={String(d)} className="conversation-choice-radio"/>{d} dias por semana</label>)}</RadioGroup>:step===5?<div className="conversation-turn"><QuestionText text={`Pronto, ${name.trim()}. Suas matérias e sua rotina já têm um espaço.`} animate/><div className="onboarding-summary"><Check size={16}/><span>{subjects.length} matérias · {days} dias por semana</span></div><p className="question-hint">Suas atividades começam como “Somente eu”. Você decide o que compartilhar.</p><button className="review-answers" onClick={()=>setStep(0)}>Revisar respostas</button></div>:null}
  {error&&<div className="entry-error" role="alert">{error}{step===5&&error.includes('usuário')&&<button onClick={()=>setStep(4)}>Alterar nome de usuário</button>}</div>}<div ref={end}/></div>
  <div className="entry-composer reference-composer">
   {busy?<LoadingPet label="Preparando seu espaço…"/>:step===0||step===4||step===2?<form onSubmit={e=>{e.preventDefault();next()}}><label className="sr-only" htmlFor="entry-answer">{questions[step]}</label>{step!==2?<input id="entry-answer" key={step} autoFocus autoComplete={step===0?'nickname':'username'} value={step===0?name:handle} maxLength={step===0?40:24} onChange={e=>step===0?setName(e.target.value):setHandle(e.target.value.toLowerCase().replace(/^@/,''))} placeholder={step===0?'Digite seu nome':'Escolha seu nome de usuário'} spellCheck={step===0} autoCapitalize={step===0?'words':'none'}/>:<span className="selected-subjects">{subjects.length?`${subjects.length} matérias selecionadas`:'Selecione suas matérias acima'}</span>}<div className="composer-footer"><span className="composer-wordmark">NIVOSTUDY<i>.</i></span><div className="composer-buttons">{step!==2&&<button className={`composer-mic ${listening?'listening':''}`} type="button" disabled={!voiceSupported||thinking} aria-label={voiceSupported?listening?'Parar gravação':'Responder por voz':'Entrada por voz indisponível neste navegador'} onClick={voice}><Mic size={15}/></button>}<button className="composer-send" type="submit" disabled={!valid||thinking} aria-label="Continuar"><ArrowRight size={18}/></button></div></div></form>:step===5?<button className="email-continue" onClick={save}>Salvar e começar<ArrowRight size={16}/></button>:null}
   <button className="conversation-back email-back" disabled={busy} aria-label="Voltar à pergunta anterior" onClick={back}><ArrowLeft size={16}/></button>
  </div>
 </main>
}
