export type Activity={id:string;owner:string;kind:string;subject:string;topic:string;seconds:number;count:number;correct:number;xp:number;data:string;visibility:string;created:number;nickname?:string;handle?:string;applause?:number;applauded?:number};
export const dayKey=(n:number)=>new Date(n).toISOString().slice(0,10);
export function metrics(events:Activity[],goal=5,now=Date.now()){
 const today=dayKey(now),midnight=Date.parse(today),weekday=(new Date(now).getUTCDay()+6)%7,weekStart=midnight-weekday*864e5;
 const recent=events.filter(e=>e.created>=now-7*864e5),week=events.filter(e=>e.created>=weekStart),prev=events.filter(e=>e.created>=weekStart-7*864e5&&e.created<weekStart);
 const active=events.filter(e=>e.count>0||e.seconds>=60||e.kind==='review'),days=new Set(active.map(e=>dayKey(e.created)));let streak=0;let cursor=midnight;if(!days.has(today))cursor-=864e5;while(days.has(dayKey(cursor))){streak++;cursor-=864e5}
 const totals=(es:Activity[])=>({seconds:es.reduce((a,e)=>a+e.seconds,0),count:es.reduce((a,e)=>a+e.count,0),correct:es.reduce((a,e)=>a+e.correct,0),xp:es.reduce((a,e)=>a+e.xp,0)});
 const total=totals(events),w=totals(week),previous=totals(prev);const c=new Set(recent.filter(e=>e.count||e.seconds>=60||e.kind==='review').map(e=>dayKey(e.created))).size;
 const components={Constância:Math.min(100,c/goal*100),Foco:Math.min(100,recent.reduce((a,e)=>a+Math.min(e.seconds,2700),0)/8100*100),Revisões:Math.min(100,recent.filter(e=>e.kind==='review').length/5*100),Questões:Math.min(100,totals(recent).count/30*100),Metas:Math.min(100,new Set(week.filter(e=>e.count||e.seconds>=60||e.kind==='review').map(e=>dayKey(e.created))).size/goal*100)};
 const score=Math.round(components.Constância*.3+components.Foco*.15+components.Revisões*.2+components.Questões*.2+components.Metas*.15);
 let bestStreak=0,current=0,last=0;for(const d of [...days].sort()){const t=Date.parse(d);current=t-last===864e5?current+1:1;bestStreak=Math.max(bestStreak,current);last=t}
 return {total,week:w,previous,score,components,streak,bestStreak,activeDays:days.size,accuracy:total.count?Math.round(total.correct/total.count*100):null,level:1+Math.floor(total.xp/100),today:totals(events.filter(e=>dayKey(e.created)===today)),bars:Array.from({length:7},(_,i)=>totals(events.filter(e=>dayKey(e.created)===dayKey(weekStart+i*864e5))).seconds),weekStart};
}
export function topicStats(events:Activity[],subject:string,topic:string){const attempts=events.filter(e=>e.subject===subject).flatMap(e=>{try{return JSON.parse(e.data).answers??[]}catch{return []}}).filter((a:any)=>a.topic===topic);const recent=attempts.slice(-20);return {count:attempts.length,accuracy:recent.length?Math.round(recent.filter((a:any)=>a.correct).length/recent.length*100):null}}
export function examReady(events:Activity[],exam:{subject:string;topics:string},now=Date.now()){const topics=JSON.parse(exam.topics) as string[];const parts=topics.map(topic=>{const stat=topicStats(events,exam.subject,topic);const studied=events.some(e=>e.subject===exam.subject&&e.topic===topic&&e.kind==='focus');const practiced=events.filter(e=>e.subject===exam.subject&&JSON.parse(e.data).answers?.some((a:any)=>a.topic===topic));const last=practiced.length?Math.max(...practiced.map(e=>e.created)):0;const recency=last?Math.max(.5,1-(now-last)/864e5*.025):0;const mastery=stat.accuracy===null?0:stat.accuracy*Math.min(1,stat.count/5)*recency;return {topic,...stat,studied,score:Math.round(mastery)}});const score=parts.length?Math.round(parts.reduce((s,p)=>s+p.score,0)/parts.length):0;return {score,parts}}
