'use client';
import {useEffect,useRef,useState} from 'react';
import {LoadingPet,Mascot} from '@/app/pet';
export default function Confirm(){
 const once=useRef(false),[error,setError]=useState(''),[ready,setReady]=useState(false),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(once.current)return;once.current=true;const params=new URLSearchParams(window.location.hash.slice(1)),access_token=params.get('access_token'),refresh_token=params.get('refresh_token'),recovery=params.get('type')==='recovery';window.history.replaceState({},'',window.location.pathname);if(!access_token||!refresh_token){setError('O link expirou ou já foi usado. Entre ou peça um novo link.');return}fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'session',access_token,refresh_token})}).then(async res=>{if(!res.ok)throw Error('Não foi possível confirmar. Peça um novo link.');if(recovery)setReady(true);else window.location.replace('/')}).catch(e=>setError(e.message))},[]);
 if(!ready&&!error)return <main className="entry-screen"><LoadingPet label="Confirmando sua conta…"/></main>;
 return <main className="entry-screen auth-screen"><section className="auth-card"><Mascot mood={busy?'thinking':'happy'}/><h1>{ready?'Uma nova senha.':'Vamos tentar de novo.'}</h1>{ready&&<form onSubmit={async e=>{e.preventDefault();if(password!==repeat){setError('As senhas precisam ser iguais.');return}setBusy(true);setError('');try{const res=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'password',password})});const data:any=await res.json();if(!res.ok)throw Error(data.error);window.location.replace('/')}catch(e){setError(e instanceof Error?e.message:'Tente novamente.');setBusy(false)}}}><label htmlFor="new-password">Nova senha</label><div className="auth-input"><input id="new-password" type="password" autoComplete="new-password" required minLength={8} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></div><label htmlFor="repeat-password">Confirmar senha</label><div className="auth-input"><input id="repeat-password" type="password" autoComplete="new-password" required minLength={8} maxLength={128} value={repeat} onChange={e=>setRepeat(e.target.value)}/></div><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar nova senha'}</button></form>}{error&&<p role="alert" className="entry-error">{error}</p>}<a href="/login" className="entry-login">Voltar ao login</a></section></main>
}
