import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/lib/db';
import {questions,defaultSubjects,publicQuestion,gradeAnswers} from '@/lib/questions';
export const dynamic='force-dynamic';
const str=(v:unknown,min=1,max=120)=>{if(typeof v!=='string'||v.trim().length<min||v.trim().length>max)throw Error('Preencha os campos corretamente.');return v.trim()};
const num=(v:unknown,min:number,max:number)=>{if(typeof v!=='number'||!Number.isInteger(v)||v<min||v>max)throw Error('Valor inválido.');return v};
const result=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:NextRequest){try{const user=await getChatGPTUser();if(!user)return result({error:'Entre com sua conta para salvar seu progresso.',signIn:true},401);const db=database(),id=user.userId;
 const profile=await db.prepare('SELECT * FROM profiles WHERE id=?').bind(id).first();
 const activities=(await db.prepare('SELECT * FROM activities WHERE owner=? ORDER BY created ASC').bind(id).all()).results;
 const exams=(await db.prepare('SELECT * FROM exams WHERE owner=? ORDER BY date').bind(id).all()).results;
 const cards=(await db.prepare('SELECT * FROM cards WHERE owner=? ORDER BY due').bind(id).all()).results;
 const active=await db.prepare('SELECT * FROM sessions WHERE owner=? AND finished=0 ORDER BY started DESC LIMIT 1').bind(id).first();
 const activeRun:any=await db.prepare('SELECT * FROM runs WHERE owner=? AND finished=0 ORDER BY started DESC LIMIT 1').bind(id).first();
 const following=(await db.prepare('SELECT p.id,p.nickname,p.handle,EXISTS(SELECT 1 FROM follows r WHERE r.owner=p.id AND r.target=?) AS mutual FROM follows f JOIN profiles p ON p.id=f.target WHERE f.owner=?').bind(id,id).all()).results;
 const feed=(await db.prepare(`SELECT a.id,a.kind,a.subject,a.topic,a.seconds,a.count,a.correct,a.xp,a.created,a.visibility,p.nickname,p.handle,(SELECT COUNT(*) FROM reactions r WHERE r.activity=a.id) AS applause,EXISTS(SELECT 1 FROM reactions r WHERE r.activity=a.id AND r.owner=?) AS applauded FROM activities a JOIN profiles p ON p.id=a.owner WHERE a.visibility='public' OR (a.visibility='friends' AND EXISTS(SELECT 1 FROM follows f WHERE f.owner=? AND f.target=a.owner) AND EXISTS(SELECT 1 FROM follows f WHERE f.owner=a.owner AND f.target=?)) ORDER BY a.created DESC LIMIT 40`).bind(id,id,id).all()).results;
 return result({profile,activities,exams,cards,active,activeRun:activeRun?{id:activeRun.id,started:activeRun.started,duration:activeRun.duration,kind:activeRun.kind,answers:JSON.parse(activeRun.draft),questions:(JSON.parse(activeRun.ids) as string[]).map(id=>publicQuestion(questions.find(q=>q.id===id)!))}:null,following,feed,subjects:defaultSubjects,questionTopics:questions.map(q=>({subject:q.subject,topic:q.topic})),viewerName:user.fullName?.split(' ')[0]??'Daniel'});
 }catch(e){console.error('nivora load',e);return result({error:'Não foi possível carregar seu progresso. Tente novamente.'},503)}}
export async function POST(req:NextRequest){try{if(req.headers.get('origin')&&req.headers.get('origin')!==req.nextUrl.origin)return result({error:'Origem inválida.'},403);const user=await getChatGPTUser();if(!user)return result({error:'Entre para continuar.',signIn:true},401);const raw=await req.text();if(raw.length>30000)return result({error:'Pedido muito grande.'},413);const b=JSON.parse(raw),db=database(),owner=user.userId,now=Date.now();const profile:any=await db.prepare('SELECT * FROM profiles WHERE id=?').bind(owner).first();
 if(b.action==='profile'){const nickname=str(b.nickname,2,40),handle=str(b.handle,3,24).toLowerCase();if(!/^[a-z0-9_]+$/.test(handle))throw Error('Use letras sem acento, números e _ no nome de usuário.');const subjects=(b.subjects as unknown[]).map(x=>str(x,1,50));if(!subjects.length||subjects.length>12||new Set(subjects).size!==subjects.length)throw Error('Selecione de 1 a 12 matérias.');const goal=num(b.goal,3,7);await db.prepare('INSERT INTO profiles(id,nickname,handle,subjects,goal,created) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET nickname=excluded.nickname,handle=excluded.handle,subjects=excluded.subjects,goal=excluded.goal').bind(owner,nickname,handle,JSON.stringify(subjects),goal,now).run();return result({ok:true})}
 if(!profile)throw Error('Personalize seu perfil antes de começar.');
 const subject=(v:unknown)=>{const s=str(v,1,50);if(!(JSON.parse(profile.subjects) as string[]).includes(s))throw Error('Adicione essa matéria ao perfil primeiro.');return s};
 if(b.action==='start'){const existing=await db.prepare('SELECT id FROM sessions WHERE owner=? AND finished=0').bind(owner).first();if(existing)throw Error('Você já tem uma sessão em andamento.');const id=crypto.randomUUID();await db.prepare('INSERT INTO sessions(id,owner,subject,topic,goal,duration,started,accumulated,running,finished) VALUES(?,?,?,?,?,?,?,0,1,0)').bind(id,owner,subject(b.subject),str(b.topic),str(b.goal,1,200),num(b.duration,0,120)*60,now).run();return result({id})}
 if(['pause','resume','finish'].includes(b.action)){const session:any=await db.prepare('SELECT * FROM sessions WHERE id=? AND owner=?').bind(str(b.id),owner).first();if(!session)throw Error('Sessão não encontrada.');if(session.finished)return result({ok:true,id:session.id});const seconds=Math.min(14400,session.accumulated+(session.running?Math.max(0,Math.floor((now-session.started)/1000)):0));
 if(b.action==='pause')await db.prepare('UPDATE sessions SET accumulated=?,running=0 WHERE id=? AND owner=? AND finished=0').bind(seconds,session.id,owner).run();
 if(b.action==='resume'&&!session.running)await db.prepare('UPDATE sessions SET started=?,running=1 WHERE id=? AND owner=? AND finished=0 AND running=0').bind(now,session.id,owner).run();
 if(b.action==='finish'){const reflection=str(b.reflection,5,1500);const priorFocus:any=await db.prepare("SELECT COUNT(*) AS count FROM activities WHERE owner=? AND kind='focus' AND created>=?").bind(owner,Date.parse(new Date(now).toISOString().slice(0,10))).first();const xp=seconds>=60&&priorFocus.count<3?10:0;await db.batch([db.prepare(`INSERT OR IGNORE INTO activities(id,owner,kind,subject,topic,seconds,count,correct,xp,data,visibility,created) SELECT id,owner,'focus',subject,topic,?,0,0,?,?,'private',? FROM sessions WHERE id=? AND owner=? AND finished=0`).bind(seconds,xp,JSON.stringify({reflection,goal:session.goal}),now,session.id,owner),db.prepare('UPDATE sessions SET accumulated=?,running=0,finished=1 WHERE id=? AND owner=? AND finished=0').bind(seconds,session.id,owner)]);return result({ok:true,id:session.id,xp})}return result({ok:true})}
 if(b.action==='startQuiz'){const unfinished=await db.prepare('SELECT id FROM runs WHERE owner=? AND finished=0').bind(owner).first();if(unfinished)throw Error('Conclua seu treino em andamento primeiro.');const s=subject(b.subject),topic=str(b.topic,1,120),difficulty=str(b.difficulty,1,20),count=num(b.count,1,20),kind=b.kind==='exam'?'exam':'quiz';const pool=questions.filter(q=>q.subject===s&&(topic==='Todos'||q.topic===topic)&&(difficulty==='Todas'||q.difficulty===difficulty)).sort(()=>Math.random()-.5);if(pool.length<count)throw Error(`Este filtro tem ${pool.length} questões. Reduza a quantidade ou escolha Todos.`);const selected=pool.slice(0,count),id=crypto.randomUUID();await db.prepare('INSERT INTO runs(id,owner,kind,ids,started,duration,finished) VALUES(?,?,?,?,?,?,0)').bind(id,owner,kind,JSON.stringify(selected.map(q=>q.id)),now,num(b.duration,0,120)*60).run();return result({id,started:now,questions:selected.map(publicQuestion),duration:b.duration*60})}
 if(b.action==='answer'){const run:any=await db.prepare('SELECT * FROM runs WHERE id=? AND owner=? AND finished=0').bind(str(b.id),owner).first();if(!run)throw Error('Treino indisponível.');const q=questions.find(q=>q.id===b.question);if(!q||!JSON.parse(run.ids).includes(q.id))throw Error('Questão inválida.');if(run.duration&&now>run.started+run.duration*1000)throw Error('O tempo de prova terminou.');const draft=JSON.parse(run.draft);draft[q.id]=num(b.answer,0,q.options.length-1);await db.prepare('UPDATE runs SET draft=? WHERE id=? AND owner=? AND finished=0').bind(JSON.stringify(draft),run.id,owner).run();return result({ok:true})}
 if(b.action==='completeQuiz'){const run:any=await db.prepare('SELECT * FROM runs WHERE id=? AND owner=?').bind(str(b.id),owner).first();if(!run)throw Error('Treino não encontrado.');const prior:any=await db.prepare('SELECT data,xp FROM activities WHERE id=? AND owner=?').bind(run.id,owner).first();if(prior)return result({...JSON.parse(prior.data),xp:prior.xp,id:run.id});const ids=JSON.parse(run.ids) as string[];const input=b.answers;if(!Array.isArray(input)||input.length!==ids.length||!ids.every(id=>input.some(a=>a.id===id)))throw Error('Respostas não correspondem ao treino.');const expired=run.duration>0&&now>run.started+run.duration*1000+10000;const answers=gradeAnswers(input.map(a=>({id:a.id,answer:expired?-1:a.answer})));const previous=(await db.prepare('SELECT data FROM activities WHERE owner=? AND created>=? AND count>0').bind(owner,Date.parse(new Date(now).toISOString().slice(0,10))).all()).results;const seen=new Set(previous.flatMap((e:any)=>JSON.parse(e.data).answers?.map((a:any)=>a.id)??[]));const xp=answers.reduce((s,a)=>s+(seen.has(a.id)?0:a.correct?8:3),0),correct=answers.filter(a=>a.correct).length,seconds=Math.max(0,Math.min(14400,Math.floor((now-run.started)/1000)));const data={answers,expired};await db.batch([db.prepare(`INSERT OR IGNORE INTO activities(id,owner,kind,subject,topic,seconds,count,correct,xp,data,visibility,created) SELECT id,owner,kind,?,?,0,?,?,?,?,'private',? FROM runs WHERE id=? AND owner=? AND finished=0`).bind(answers[0].subject,new Set(answers.map(a=>a.topic)).size===1?answers[0].topic:'Vários assuntos',answers.length,correct,xp,JSON.stringify({...data,seconds}),now,run.id,owner),db.prepare('UPDATE runs SET finished=1 WHERE id=? AND owner=?').bind(run.id,owner)]);return result({...data,id:run.id,xp})}
 if(b.action==='exam'){const date=str(b.date,10,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||date<new Date(now).toISOString().slice(0,10))throw Error('Escolha uma data a partir de hoje.');const topics=(b.topics as unknown[]).map(x=>str(x,1,120));if(!topics.length||topics.length>20)throw Error('Informe os conteúdos da prova.');await db.prepare('INSERT INTO exams(id,owner,name,subject,date,topics) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,str(b.name),subject(b.subject),date,JSON.stringify([...new Set(topics)])).run();return result({ok:true})}
 if(b.action==='removeExam'){await db.prepare('DELETE FROM exams WHERE id=? AND owner=?').bind(str(b.id),owner).run();return result({ok:true})}
 if(b.action==='card'){await db.prepare('INSERT INTO cards(id,owner,subject,front,back,due,interval) VALUES(?,?,?,?,?,?,0)').bind(crypto.randomUUID(),owner,subject(b.subject),str(b.front,3,500),str(b.back,3,2000),now).run();return result({ok:true})}
 if(b.action==='review'){const card:any=await db.prepare('SELECT * FROM cards WHERE id=? AND owner=?').bind(str(b.id),owner).first();if(!card||card.due>now)throw Error('Esse cartão ainda não está disponível para revisão.');const rating=num(b.rating,0,3);const interval=rating===0?0:rating===1?Math.max(1,Math.round(card.interval*1.2)):rating===2?Math.max(3,Math.round(card.interval*2)):Math.max(5,Math.round(card.interval*3));const due=now+(rating===0?600000:interval*864e5),id=card.id+'-'+card.due;await db.batch([db.prepare(`INSERT OR IGNORE INTO activities(id,owner,kind,subject,topic,seconds,count,correct,xp,data,visibility,created) SELECT ?,owner,'review',subject,'Flashcards',0,0,0,5,?,'private',? FROM cards WHERE id=? AND owner=? AND due=?`).bind(id,JSON.stringify({card:card.id,rating}),now,card.id,owner,card.due),db.prepare('UPDATE cards SET due=?,interval=? WHERE id=? AND owner=? AND due=?').bind(due,interval,card.id,owner,card.due)]);return result({ok:true,due})}
 if(b.action==='visibility'){if(!['private','friends','public'].includes(b.visibility))throw Error('Privacidade inválida.');await db.prepare('UPDATE activities SET visibility=? WHERE id=? AND owner=?').bind(b.visibility,str(b.id),owner).run();return result({ok:true})}
 if(b.action==='follow'){const target:any=await db.prepare('SELECT id FROM profiles WHERE handle=?').bind(str(b.handle,3,24).toLowerCase()).first();if(!target||target.id===owner)throw Error('Usuário não encontrado.');await db.prepare('INSERT OR IGNORE INTO follows(id,owner,target) VALUES(?,?,?)').bind(owner+':'+target.id,owner,target.id).run();return result({ok:true})}
 if(b.action==='unfollow'){await db.prepare('DELETE FROM follows WHERE owner=? AND target=?').bind(owner,str(b.id)).run();return result({ok:true})}
 if(['applaud','comment','comments'].includes(b.action)){const id=str(b.id);const activity:any=await db.prepare(`SELECT id FROM activities a WHERE id=? AND (owner=? OR visibility='public' OR (visibility='friends' AND EXISTS(SELECT 1 FROM follows f WHERE f.owner=? AND f.target=a.owner) AND EXISTS(SELECT 1 FROM follows f WHERE f.owner=a.owner AND f.target=?)))`).bind(id,owner,owner,owner).first();if(!activity)return result({error:'Atividade indisponível.'},404);if(b.action==='applaud'){const key=owner+':'+id;const existing=await db.prepare('SELECT id FROM reactions WHERE id=?').bind(key).first();if(existing)await db.prepare('DELETE FROM reactions WHERE id=?').bind(key).run();else await db.prepare('INSERT INTO reactions(id,owner,activity) VALUES(?,?,?)').bind(key,owner,id).run();return result({ok:true})}if(b.action==='comment')await db.prepare('INSERT INTO comments(id,owner,activity,body,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),owner,id,str(b.body,1,500),now).run();const comments=(await db.prepare('SELECT c.id,c.body,c.created,p.nickname FROM comments c JOIN profiles p ON p.id=c.owner WHERE activity=? ORDER BY created DESC LIMIT 30').bind(id).all()).results;return result({comments})}
 if(b.action==='deleteComment'){await db.prepare('DELETE FROM comments WHERE id=? AND owner=?').bind(str(b.id),owner).run();return result({ok:true})}
 return result({error:'Ação desconhecida.'},400);
 }catch(e){const message=e instanceof Error?e.message:'';console.error('nivora write',e);return result({error:message.includes('UNIQUE')?'Esse nome de usuário já está em uso.':message.includes('D1')||message.includes('SQL')?'Não foi possível salvar. Tente novamente.':message||'Pedido inválido.'},400)}}
